Add module for managing L7 firewall rules on MR devices
CiscoDevNet/ansible-meraki pull request #382
Opened 2022-11-15 00:58 UTC by joshuajcoronado

This module allows users to manage l7 firewall rules on an MR device using the /networks/{networkId}/wireless/ssids/{number}/firewall/l7FirewallRules API. 

I am unable to run integration tests, so I can't verify that I got every base covered, i used the existing mx l7 and mr l3 firewall rules modules as a base

2022-11-15 11:24 UTC, kbreit commented
Did you copy the MX module and rename the proper sections to MR?

2022-11-15 22:12 UTC, y0rune commented
I can not test in the Meraki Sandbox :( I do not have permission to create a network :(
```
yorune@MacBook-Pro ~/git/ansible_collections/cisco/meraki joshuajcoronado/meraki_mr_l7_firewall $ ansible-test network-integration --allow-unsupported meraki_mr_l7_firewall
Running meraki_mr_l7_firewall integration test role
[WARNING]: running playbook inside collection cisco.meraki

PLAY [meraki] ******************************************************************

TASK [meraki_mr_l7_firewall : Create network] **********************************
[WARNING]: Platform darwin on host localhost is using the discovered Python
interpreter at /opt/homebrew/opt/python@3.11/bin/python3.11, but future
installation of another Python interpreter could change the meaning of that
path. See https://docs.ansible.com/ansible-
core/2.14/reference_appendices/interpreter_discovery.html for more information.
fatal: [localhost]: FAILED! => {"ansible_facts": {"discovered_interpreter_python": "/opt/homebrew/opt/python@3.11/bin/python3.11"}, "changed": false, "msg": 403, "response": "OK (unknown bytes)", "status": 403, "url": "https://api.meraki.com/api/v1/organizations/549236/networks"}

TASK [meraki_mr_l7_firewall : Delete wireless SSID] ****************************
fatal: [localhost]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'net' is undefined. 'net' is undefined\n\nThe error appears to be in '/Users/yorune/git/ansible_collections/cisco/meraki/tests/output/.tmp/integration/meraki_mr_l7_firewall-312m3ipq-ÅÑŚÌβŁÈ/tests/integration/targets/meraki_mr_l7_firewall/tasks/tests.yml': line 465, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n  always:\n    - name: Delete wireless SSID\n      ^ here\n"}

PLAY RECAP *********************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=2    skipped=0    rescued=0    ignored=0

NOTICE: To resume at this test target, use the option: --start-at meraki_mr_l7_firewall
FATAL: Command "ansible-playbook meraki_mr_l7_firewall-u4yihm7y.yml -i inventory.networking" returned exit status 2.
```

2022-11-16 12:47 UTC, kbreit requested changes

2022-11-16 12:47 UTC, kbreit commented on tests/integration/targets/meraki_mr_l7_firewall/tasks/tests.yml
> +  - name: Create network
This task needs to register a variable since it's used in the next task.

2022-11-16 16:33 UTC, joshuajcoronado commented
@kbreit changes pushed

2022-11-16 22:17 UTC, y0rune commented
Today, I have tested the playbook but again I do not have permission on the claiming new devices. So I wrote the email to dev support.

If I may ask how did you test @joshuajcoronado the module?

2022-11-16 22:21 UTC, joshuajcoronado commented
@y0rune i tested the module locally, using my own networks. I was unable to get the integration tests working, and those tests are heavily borrowed from the mr l3 and mx l7 tests.

2022-11-16 23:04 UTC, y0rune commented
@joshuajcoronado amazing! I do not have meraki for my own. When I know the way to test it in the dev env I am going to write here. Thank your for answer!

2022-11-18 02:28 UTC, kbreit requested changes

2022-11-18 21:38 UTC, joshuajcoronado commented on tests/integration/targets/meraki_mr_l7_firewall/tasks/tests.yml
> +  - name: Query firewall rules
Added

2022-11-20 01:53 UTC, kbreit requested changes

2022-11-20 01:53 UTC, kbreit commented on tests/integration/targets/meraki_mr_l7_firewall/tasks/tests.yml
> +  - name: Assert multiple_rules.data.rules | length == 3
This is failing as the length isn't matching. The output I see is below as well.

```
        "data": {
            "rules": [
                {
                    "application_category": {
                        "id": "meraki:layer7/category/27",
                        "name": "Advertising"
                    },
                    "policy": "deny",
                    "type": "applicationCategory"
                },
                {
                    "policy": "deny",
                    "port": "8080",
                    "type": "port"
                }
            ]
        },
```

```
TASK [meraki_mr_l7_firewall : Assert multiple_rules.data.rules | length == 3] ***
fatal: [localhost]: FAILED! => {
    "assertion": "multiple_rules.data.rules | length == 3",
    "changed": false,
    "evaluated_to": false,
    "msg": "Assertion failed"
}
```

2022-11-21 17:35 UTC, joshuajcoronado commented
okay, was able to get the integration tests runnin locally, passing now

2022-11-21 19:40 UTC, joshuajcoronado commented
@kbreit this is ready too

2022-11-21 19:43 UTC, kbreit commented
> @kbreit this is ready too

Just released 2.12.0 as you posted this. I can do a 2.13.0 easily enough of course.

2022-11-21 19:44 UTC, joshuajcoronado commented
this and https://github.com/CiscoDevNet/ansible-meraki/pull/384 would be great

2022-11-21 19:44 UTC, kbreit commented
This passed integration test and looks good so I am merging. Again, thank you so much for you contribution.

2022-11-21 19:44 UTC, merged