Add ax_enabled for 5Ghz band
CiscoDevNet/ansible-meraki pull request #422
Opened 2023-01-17 09:32 UTC by hannut

2023-01-17 10:36 UTC, hannut commented
I fixed the indentations with ALEFix. Seems that it also changed quotes

2023-01-17 13:17 UTC, hannut commented
First patch adds the setting. Second one is for tests to go trough. I think it's ready

2023-01-18 02:08 UTC, kbreit requested changes

2023-01-18 05:31 UTC, hannut commented on plugins/modules/meraki_mr_rf_profile.py
> +        if meraki.params['five_ghz_settings']['ax_enabled'] is not None:
There is ax setting on both bands on the dashboard. However I tried flipping the 5ghz setting on and off on the dashboard and then tried to change it with ansible and it actually doesn't do anything. Maybe the public api is behind what can be done on the meraki dashboard

![Kuvakaappaus - 2023-01-18 07-23-05](https://user-images.githubusercontent.com/10574295/213091927-c53852a9-ae3c-49cc-a7d9-0beed534a3ae.png)

2023-01-18 13:33 UTC, closed without merging

2023-01-18 13:50 UTC, kbreit commented
@hannut Is there a reason you're closing this PR? The 2.4ghz is doable. It's just the 5ghz setting that is invalid in the API.